# Generated by Django 3.0.4 on 2021-01-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_Type', models.CharField(choices=[('plumbing', 'Plumbing'), ('electric', 'Electric'), ('painting', 'Painting'), ('deep cleaning', 'Deep Cleaning')], max_length=15)),
                ('Request_Desc', models.CharField(max_length=150)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(choices=[('rj', 'Rajasthan'), ('kr', 'Karnataka'), ('bi', 'Bihar'), ('guj', 'Gujrat'), ('maharashtra', 'Maharashtra'), ('goa', 'Goa'), ('sikkim', 'Sikkim'), ('bang', 'Banglore')], max_length=20)),
                ('Pin_Code', models.IntegerField()),
                ('Alternate_Phone_N', models.IntegerField()),
            ],
        ),
    ]
