# Generated by Django 3.0.4 on 2021-01-07 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asApp', '0002_request_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Request_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
