# Generated by Django 3.0.4 on 2021-01-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asApp', '0003_auto_20210107_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Pending', 'pending'), ('In Progress', 'in progress'), ('Completed', 'completed')], max_length=15)),
                ('Remark', models.CharField(max_length=150)),
            ],
        ),
    ]
