# Generated by Django 3.0.4 on 2021-01-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asApp', '0004_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='request',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='asApp.Request'),
        ),
    ]
