# Generated by Django 3.0.4 on 2021-01-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asApp', '0007_auto_20210107_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='Remark',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='Status',
            field=models.CharField(choices=[('Pending', 'pending'), ('In Progress', 'in progress'), ('Completed', 'completed')], max_length=15, null=True),
        ),
    ]
