# Generated by Django 3.0.4 on 2021-01-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asApp', '0008_auto_20210107_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='Remark',
            field=models.CharField(default='', max_length=150),
        ),
    ]
