# Generated by Django 3.0.4 on 2021-01-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asApp', '0009_auto_20210107_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='Remark',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='update',
            name='Status',
            field=models.CharField(choices=[('Pending', 'pending'), ('In Progress', 'in progress'), ('Completed', 'completed')], default='Pending', max_length=15),
        ),
    ]
